name: Deploy Lambda Function

on:
  push:
    branches:
      - main  # Cambia esto si usas otra rama

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Zip files
        run: zip -r deployment.zip lambda.js node_modules package.json

      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: "us-west-1"
          function_name: "jiraWebhookLambda"
          zip_file: "deployment.zip"
